lib/my_app_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MyAppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyAppWeb do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/accounts", AccountController
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MyAppWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/my_app_web/controllers/session_controller.ex
defmodule MyAppWeb.SessionController do
  use MyAppWeb, :controller

  alias MyApp.Accounts
  alias MyApp.Services.Encryptr

  def new(conn, _params) do
    if Plug.Conn.get_session(conn, :current_user) do
      Phoenix.Controller.redirect(conn, to: "/")
    else
      render(conn, "new.html")
    end
  end

  def create(conn, params) do
    case Accounts.get_user_by(email: String.downcase(params["email"])) do
      {:ok, user} ->
        case Encryptr.validate_password(params["password"], user.password_hash) do
          true ->
            create_session_conds(conn, user)

          _ ->
            conn
            |> put_flash(:error, "Incorrect email or password.")
            |> render("new.html")
        end

      {:error, Ecto.NoResultsError} ->
        conn
        |> put_flash(:error, "No users found with that email address.")
        |> render("new.html")
    end
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:current_user)
    |> redirect(to: "/")
  end

  defp create_session_conds(conn, user) do
    cond do
      !user.verified and user.active ->
        conn
        |> put_session(:unverified_user, user.id)
        |> put_flash(
          :error,
          "Your account is not verified."
        )
        |> redirect(to: "/login")

      !user.account.active or !user.active ->
        conn
        |> put_session(:unverified_user, user.id)
        |> put_flash(
          :error,
          "Your account is currently inactive."
        )
        |> render("new.html")

      user.account.active and user.verified and user.active ->
        conn
        |> put_session(:current_user, user)
        |> redirect(to: "/")

      true ->
        conn |> render("new.html")
    end
  end
end

lib/my_app_web/views/session_view.ex
defmodule MyAppWeb.SessionView do
  use MyAppWeb, :view
end

lib/my_app_web/templates/session/new.html.eex
<div class="column is-one-third is-offset-one-third">
  <div class="box wb-box">
    <hr/>
    <%= form_for @conn, Routes.session_path(@conn, :create), [name: :session], fn f -> %>
      <div class="field">
        <label class="label">Email Address</label>
        <p class="control has-icons-left">
          <%= email_input f, :email, autofocus: "on", placeholder: "Email", class: "input" %>
          <span class="icon is-small is-left">
            <ion-icon name="mail-outline"></ion-icon>
          </span>
        </p>
      </div>
      <div class="field">
        <label class="label">Password</label>
        <p class="control has-icons-left">
          <%= password_input f, :password, autocomplete: "off", placeholder: "Password", class: "input" %>
          <span class="icon is-small is-left">
            <ion-icon name="lock-closed-outline"></ion-icon>
          </span>
        </p>
      </div>
      <br/>
      <div class="field">
        <p class="control">
          <%= submit "Log In", class: "is-primary shadow button is-fullwidth" %>
        </p>
      </div>
    <% end %>
    <br/>
  </div>
</div>